# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ unit-test ]
  pull_request:
    branches: [ unit-test ]

jobs:
  build: 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        
    #services:
     # mysql:
     #   image: mysql:5.7
     #   env:
     #     MYSQL_ROOT_PASSWORD: 123456
     #   ports:
     #     - 3366
     #   options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
  #  - run: sudo service mysql start
#    - run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3366'] }} -u root -p "123456" < qlkd.sql
 #  - run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3366'] }} -u root -p "123456" -e "SHOW DATABASES"
  #  - run: node scripts/ci ${{ job.services.mysql.ports['3366'] }}
    - run: npm test
